export interface FamilyRelation {
  person: string;
  related_to: string;
  relationship_type: "bapak" | "ibu" | "pasangan" | "anak";
}

const rawFamilyData: FamilyRelation[] = [
  { person: "Meutia Hatta", related_to: "Mohammad Hatta", relationship_type: "bapak" },
  { person: "Halida Hatta", related_to: "Mohammad Hatta", relationship_type: "bapak" },
  { person: "Gemala Hatta", related_to: "Mohammad Hatta", relationship_type: "bapak" },
  { person: "Dolly Salim", related_to: "Agus Salim", relationship_type: "bapak" },
  { person: "Bibsy Soenharjo", related_to: "Agus Salim", relationship_type: "bapak" },
  { person: "Violet Hanifah Salim", related_to: "Agus Salim", relationship_type: "bapak" },
  { person: "Islam Salim", related_to: "Agus Salim", relationship_type: "bapak" },
  { person: "Ja'afar dari Negeri Sembilan", related_to: "Abdul Rahman dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Tunku Tan Sri Abdullah", related_to: "Abdul Rahman dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Tuanku Bahiyah", related_to: "Abdul Rahman dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Munawir dari Negeri Sembilan", related_to: "Abdul Rahman dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Ilham Aidit", related_to: "D. N. Aidit", relationship_type: "bapak" },
  { person: "Tunku Naquiyuddin", related_to: "Ja'afar dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Tunku Imran", related_to: "Ja'afar dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Tunku Nadzaruddin", related_to: "Ja'afar dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Mirta Kartohadiprodjo", related_to: "Sutan Takdir Alisjahbana", relationship_type: "bapak" },
  { person: "Samiati Alisjahbana", related_to: "Sutan Takdir Alisjahbana", relationship_type: "bapak" },
  { person: "Sofyan Alisjahbana", related_to: "Sutan Takdir Alisjahbana", relationship_type: "bapak" },
  { person: "Sri Artaria Alisjahbana", related_to: "Sutan Takdir Alisjahbana", relationship_type: "bapak" },
  { person: "Iskandar Alisjahbana", related_to: "Sutan Takdir Alisjahbana", relationship_type: "bapak" },
  { person: "Siti Rabyah Parvati Sjahrir", related_to: "Sutan Sjahrir", relationship_type: "bapak" },
  { person: "Kriya Arsyah Sjahrir", related_to: "Sutan Sjahrir", relationship_type: "bapak" },
  { person: "Hamdan Sheikh Tahir", related_to: "Tahir Jalaluddin Al-Azhari", relationship_type: "bapak" },
  { person: "Irwan Usmar Ismail", related_to: "Usmar Ismail", relationship_type: "bapak" },
  { person: "Dede Yusuf", related_to: "Roestam Effendi", relationship_type: "bapak" },
  { person: "Camelia Malik", related_to: "Djamaludin Malik", relationship_type: "bapak" },
  { person: "Edwin Hidayat Abdullah", related_to: "Taufik Abdullah", relationship_type: "bapak" },
  { person: "Rano Karno", related_to: "Soekarno M. Noer", relationship_type: "bapak" },
  { person: "Suti Karno", related_to: "Soekarno M. Noer", relationship_type: "bapak" },
  { person: "Tino Karno", related_to: "Soekarno M. Noer", relationship_type: "bapak" },
  { person: "Endang Saifudin Ashari", related_to: "Muhammad Isa Anshary", relationship_type: "bapak" },
  { person: "Adiwarsita Adinegoro", related_to: "Adinegoro", relationship_type: "bapak" },
  { person: "Roeshan Roesli", related_to: "Marah Roesli", relationship_type: "bapak" },
  { person: "Rustam Abdullah Sani", related_to: "Ahmad Boestamam", relationship_type: "bapak" },
  { person: "Ibrahim Irwan Prayitno", related_to: "Irwan Prayitno", relationship_type: "bapak" },
  { person: "Roosdinal Salim", related_to: "Emil Salim", relationship_type: "bapak" },
  { person: "Amelia Farina Salim", related_to: "Emil Salim", relationship_type: "bapak" },
  { person: "Puan Maharani", related_to: "Taufiq Kiemas", relationship_type: "bapak" },
  { person: "Farid Prawiranegara", related_to: "Syafruddin Prawiranegara", relationship_type: "bapak" },
  { person: "Muhammad Iqbal (politikus PPP)", related_to: "Bachtiar Chamsyah", relationship_type: "bapak" },
  { person: "Emil Arifin", related_to: "Bustanil Arifin", relationship_type: "bapak" },
  { person: "Alwin Arifin", related_to: "Bustanil Arifin", relationship_type: "bapak" },
  { person: "Hamka", related_to: "Abdul Karim Amrullah", relationship_type: "bapak" },
  { person: "Abdul Wadud Karim Amrullah", related_to: "Abdul Karim Amrullah", relationship_type: "bapak" },
  { person: "Abdul Kuddus Karim Amrullah", related_to: "Abdul Karim Amrullah", relationship_type: "bapak" },
  { person: "Abdul Bari Karim Amrullah", related_to: "Abdul Karim Amrullah", relationship_type: "bapak" },
  { person: "Dipo Latief", related_to: "Abdul Latief", relationship_type: "bapak" },
  { person: "Medina Latief Harjani", related_to: "Abdul Latief", relationship_type: "bapak" },
  { person: "Fahira Fahmi Idris", related_to: "Fahmi Idris", relationship_type: "bapak" },
  { person: "Fahrina Fahmi Idris", related_to: "Fahmi Idris", relationship_type: "bapak" },
  { person: "Rusydi Hamka", related_to: "Hamka", relationship_type: "bapak" },
  { person: "Irfan Hamka", related_to: "Hamka", relationship_type: "bapak" },
  { person: "Aliyah Hamka", related_to: "Hamka", relationship_type: "bapak" },
  { person: "Afif Hamka", related_to: "Hamka", relationship_type: "bapak" },
  { person: "Fathiyah Hamka", related_to: "Hamka", relationship_type: "bapak" },
  { person: "Amir Syakib", related_to: "Hamka", relationship_type: "bapak" },
  { person: "Dino Patti Djalal", related_to: "Hasyim Djalal", relationship_type: "bapak" },
  { person: "Cahya Kamila", related_to: "Misbach Yusa Biran", relationship_type: "bapak" },
  { person: "Sukma Ayu", related_to: "Misbach Yusa Biran", relationship_type: "bapak" },
  { person: "Abdul Karim Amrullah", related_to: "Muhammad Amrullah", relationship_type: "bapak" },
  { person: "Abdul Rahman dari Negeri Sembilan", related_to: "Muhammad dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Tunku 'Abidin Muhriz", related_to: "Muhriz dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Tunku Ali Redhauddin", related_to: "Muhriz dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Tunku Alif Hussein Saifuddin Al-Amin", related_to: "Muhriz dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Tuanku Najihah", related_to: "Tunku Besar Burhanuddin", relationship_type: "bapak" },
  { person: "Tunku Kurshiah", related_to: "Tunku Besar Burhanuddin", relationship_type: "bapak" },
  { person: "Mahmud dari Siak", related_to: "Abdul Jalil Syah dari Siak", relationship_type: "bapak" },
  { person: "Nan Achnas", related_to: "Nas Achnas", relationship_type: "bapak" },
  { person: "Rezlan Ishar Jenie", related_to: "Adlinsjah Jenie", relationship_type: "bapak" },
  { person: "Muhammad dari Negeri Sembilan", related_to: "Antah dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Tunku Besar Burhanuddin", related_to: "Antah dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Roestam Anwar", related_to: "Anwar Sutan Saidi", relationship_type: "bapak" },
  { person: "Roby Irwanto", related_to: "Basril Djabar", relationship_type: "bapak" },
  { person: "Vino G. Bastian", related_to: "Bastian Tito", relationship_type: "bapak" },
  { person: "Murnizal Dahlan", related_to: "Dahlan Ibrahim", relationship_type: "bapak" },
  { person: "Yazeed Djamin", related_to: "Datuk Djamin", relationship_type: "bapak" },
  { person: "Chaula Luthfia Sukasah", related_to: "Djamaloeddin", relationship_type: "bapak" },
  { person: "Ilya Arslaan Sjahroezah", related_to: "Djohan Sjahroezah", relationship_type: "bapak" },
  { person: "Athari Gauthi Ardi", related_to: "Epyardi Asda", relationship_type: "bapak" },
  { person: "Irman Gusman", related_to: "Gusman Gaus", relationship_type: "bapak" },
  { person: "Ismail Ning", related_to: "Hasyim Ning", relationship_type: "bapak" },
  { person: "Akhiroel Jahja", related_to: "Jahja Datoek Kajo", relationship_type: "bapak" },
  { person: "Daan Jahja", related_to: "Jahja Datoek Kajo", relationship_type: "bapak" },
  { person: "Sagaf Jahja", related_to: "Jahja Datoek Kajo", relationship_type: "bapak" },
  { person: "Joserizal Jurnalis", related_to: "Jurnalis Kamil", relationship_type: "bapak" },
  { person: "Adrin Kahar", related_to: "Kaharudin Datuk Rangkayo Basa", relationship_type: "bapak" },
  { person: "Amrin Kahar", related_to: "Kaharudin Datuk Rangkayo Basa", relationship_type: "bapak" },
  { person: "Djohari Kahar", related_to: "Kaharudin Datuk Rangkayo Basa", relationship_type: "bapak" },
  { person: "Desi Anwar", related_to: "Khaidir Anwar", relationship_type: "bapak" },
  { person: "Dewi Fortuna Khaidir Anwar", related_to: "Khaidir Anwar", relationship_type: "bapak" },
  { person: "Sri Danti Anwar", related_to: "Khaidir Anwar", relationship_type: "bapak" },
  { person: "Jombang Santani Khairen", related_to: "Khairul Jasmi", relationship_type: "bapak" },
  { person: "Radin dari Negeri Sembilan", related_to: "Lenggang dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Tuanku Imam", related_to: "Lenggang dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "O.B. Sjaaf", related_to: "M. Syaaf", relationship_type: "bapak" },
  { person: "Ahmad Faisal Marzuki", related_to: "Marzuki Yatim", relationship_type: "bapak" },
  { person: "Amelia Naim Indrajaya", related_to: "Mochtar Naim", relationship_type: "bapak" },
  { person: "Ahlan B. Razif", related_to: "Mohamad Razif", relationship_type: "bapak" },
  { person: "Ahzam B. Razif", related_to: "Mohamad Razif", relationship_type: "bapak" },
  { person: "Kumhal Djamil", related_to: "Mohammad Djamil", relationship_type: "bapak" },
  { person: "Sjamsidar Isa", related_to: "Mohamad Isa", relationship_type: "bapak" },
  { person: "Kamil Bahren Pasha", related_to: "Muslim Kasim", relationship_type: "bapak" },
  { person: "Jajang C. Noer", related_to: "Nazir Datuk Pamuncak", relationship_type: "bapak" },
  { person: "Ade Rezki Pratama", related_to: "Nelson Septiadi", relationship_type: "bapak" },
  { person: "Hadi Nur", related_to: "Nur Anas Djamil", relationship_type: "bapak" },
  { person: "Raja Sapta Oktohari", related_to: "Oesman Sapta Odang", relationship_type: "bapak" },
  { person: "Antah dari Negeri Sembilan", related_to: "Radin dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Nian S. Djoemena", related_to: "Rahman Tamin", relationship_type: "bapak" },
  { person: "Svida Alisjahbana", related_to: "Sofyan Alisjahbana", relationship_type: "bapak" },
  { person: "Riyanto Sofyan", related_to: "Sofyan Ponda", relationship_type: "bapak" },
  { person: "Ahmad Fadly", related_to: "Suir Syam", relationship_type: "bapak" },
  { person: "Harsja W. Bachtiar", related_to: "Sutan Adam Bachtiar", relationship_type: "bapak" },
  { person: "Arwin Rasyid", related_to: "Sutan Mohammad Rasjid", relationship_type: "bapak" },
  { person: "Tarmizi Taher", related_to: "Taher Marah Soetan", relationship_type: "bapak" },
  { person: "Sjahriar Rasad", related_to: "Zainuddin Rasad", relationship_type: "bapak" },
  { person: "Nirina Zubir", related_to: "Zubir Amin", relationship_type: "bapak" },
  { person: "Aidil Chandra Salim", related_to: "Ferdy Salim", relationship_type: "bapak" },
  { person: "Felia Salim", related_to: "Ferdy Salim", relationship_type: "bapak" },
  { person: "Harry Roesli", related_to: "Roeshan Roesli", relationship_type: "bapak" },
  { person: "Utami Roesli", related_to: "Roeshan Roesli", relationship_type: "bapak" },
  { person: "Sonya Roesma", related_to: "A. Roesma", relationship_type: "bapak" },
  { person: "Sirajuddin Abbas", related_to: "Abbas Qadhi Ladang Laweh", relationship_type: "bapak" },
  { person: "Halimah Agustina Kamil", related_to: "Abdullah Kamil", relationship_type: "bapak" },
  { person: "Huriah Adam", related_to: "Adam B.B.", relationship_type: "bapak" },
  { person: "Boestanoel Arifin Adam", related_to: "Adam B.B.", relationship_type: "bapak" },
  { person: "Akio Alfiano Tamala", related_to: "Ambiar Tamala", relationship_type: "bapak" },
  { person: "Perdana Putra Minang", related_to: "Bonny Z. Minang", relationship_type: "bapak" },
  { person: "Biandra Nurully Minang", related_to: "Bonny Z. Minang", relationship_type: "bapak" },
  { person: "Teuku Nanta Seutia", related_to: "Datuk Makhudum Sati", relationship_type: "bapak" },
  { person: "Mansoer Daoed Dt. Palimo Kayo", related_to: "Daud Rasyidi", relationship_type: "bapak" },
  { person: "Ismet D. Tahir", related_to: "Djilis Tahir", relationship_type: "bapak" },
  { person: "Vega Antares", related_to: "Herry Setianegara", relationship_type: "bapak" },
  { person: "Idham Samawi", related_to: "HM. Samawi", relationship_type: "bapak" },
  { person: "Dahlan Djambek", related_to: "Muhammad Jamil Jambek", relationship_type: "bapak" },
  { person: "Saadoeddin Djambek", related_to: "Muhammad Jamil Jambek", relationship_type: "bapak" },
  { person: "Zainal Abidin Djambek", related_to: "Muhammad Jamil Jambek", relationship_type: "bapak" },
  { person: "Taufiq Ismail", related_to: "Abdul Gaffar Ismail", relationship_type: "bapak" },
  { person: "Gina Sutan Aswar", related_to: "Sutan Aswar", relationship_type: "bapak" },
  { person: "Saiful Sutan Aswar", related_to: "Sutan Aswar", relationship_type: "bapak" },
  { person: "Sativa Sutan Aswar", related_to: "Sutan Aswar", relationship_type: "bapak" },
  { person: "Budi Satria Isman", related_to: "Jakub Isman", relationship_type: "bapak" },
  { person: "Suci Madiarti Isman", related_to: "Jakub Isman", relationship_type: "bapak" },
  { person: "Syahrial Loetan", related_to: "Loetan St. Toenaro", relationship_type: "bapak" },
  { person: "Ahwil Luthan", related_to: "Loetan St. Toenaro", relationship_type: "bapak" },
  { person: "Hendri Septa", related_to: "Muhammad Asli Chaidir", relationship_type: "bapak" },
  { person: "Budi Arwan", related_to: "Aristo Munandar", relationship_type: "bapak" },
  { person: "Zulheri Rani", related_to: "Rani Ismael", relationship_type: "bapak" },
  { person: "Mirza Adityaswara", related_to: "Sutan Remy Sjahdeini", relationship_type: "bapak" },
  { person: "Aida Nurmala", related_to: "Sjamsidar Isa", relationship_type: "bapak" },
  { person: "Benny Dwifa Yuswir", related_to: "Yuswir Arifin", relationship_type: "bapak" },
  { person: "Dendy Prasetya", related_to: "Zulkarnaen Djabar", relationship_type: "bapak" },
  { person: "Indah Nugrahani", related_to: "Zulkarnaen Djabar", relationship_type: "bapak" },
  { person: "Zulhelfi", related_to: "Bakhtar", relationship_type: "bapak" },
  { person: "Fidri Arnaldy", related_to: "Djohari Kahar", relationship_type: "bapak" },
  { person: "Syarifah Nawawi", related_to: "Nawawi Soetan Makmoer", relationship_type: "bapak" },
  { person: "Ivan Rizal Sini", related_to: "Rizal Sini", relationship_type: "bapak" },
  { person: "Aqsa Sutan Aswar", related_to: "Saiful Sutan Aswar", relationship_type: "bapak" },
  { person: "Aero Sutan Aswar", related_to: "Saiful Sutan Aswar", relationship_type: "bapak" },
  { person: "Farid Anfasa Moeloek", related_to: "Abdul Moeloek", relationship_type: "bapak" },
  { person: "Nukman Moeloek", related_to: "Abdul Moeloek", relationship_type: "bapak" },
  { person: "Dara Jingga", related_to: "Srimat Tribhuwanaraja Mauli Warmadewa", relationship_type: "bapak" },
  { person: "Dara Petak", related_to: "Srimat Tribhuwanaraja Mauli Warmadewa", relationship_type: "bapak" },
  { person: "Cut Nya' Dhien", related_to: "Teuku Nanta Seutia", relationship_type: "bapak" },
  { person: "M. Gunawan Yasni", related_to: "Zainul Yasni", relationship_type: "bapak" },
  { person: "Agus Salim", related_to: "Sutan Mohamad Salim", relationship_type: "bapak" },
  { person: "Chalid Salim", related_to: "Sutan Mohamad Salim", relationship_type: "bapak" },
  { person: "Siti Danilah Salim", related_to: "Sutan Mohamad Salim", relationship_type: "bapak" },
  { person: "Baay Salim", related_to: "Sutan Mohamad Salim", relationship_type: "bapak" },
  { person: "Sherina Munaf", related_to: "Triawan Munaf", relationship_type: "bapak" },
  { person: "Harun Al-Rasjid Zain", related_to: "Sutan Muhammad Zain", relationship_type: "bapak" },
  { person: "Yetty Rizali Noor", related_to: "Sutan Muhammad Zain", relationship_type: "bapak" },
  { person: "Zairin Zain", related_to: "Sutan Muhammad Zain", relationship_type: "bapak" },
  { person: "Sutan Amrull", related_to: "Abdul Wadud Karim Amrullah", relationship_type: "bapak" },
  { person: "Muhriz dari Negeri Sembilan", related_to: "Munawir dari Negeri Sembilan", relationship_type: "bapak" },
  { person: "Siti Dewi Sutan Assin", related_to: "Sutan Assin", relationship_type: "bapak" },
  { person: "Mansyur Sutan Assin", related_to: "Sutan Assin", relationship_type: "bapak" },
  { person: "Muhibuddin Waly", related_to: "Muhammad Waly Al-Khalidy", relationship_type: "bapak" },
  { person: "Mawardi Waly", related_to: "Muhammad Waly Al-Khalidy", relationship_type: "bapak" },
  { person: "Fatmawati", related_to: "Hasan Din", relationship_type: "bapak" },
  { person: "Nadirman Haska", related_to: "Hasnawi Karim", relationship_type: "bapak" },
  { person: "Muhammad Lutfi", related_to: "Firdaus Wadjdi", relationship_type: "bapak" },
  { person: "Sutan Emir Hidayat", related_to: "Muhammad Taufiq Thaib", relationship_type: "bapak" },
  { person: "Fauziah Fauzan", related_to: "Fauzan Misra el-Muhammady", relationship_type: "bapak" },
  { person: "Muhammad Fuad Nasar", related_to: "Nasaruddin Latif", relationship_type: "bapak" },
  { person: "Rabi'ah Jamil", related_to: "Muhammad Jamil Jaho", relationship_type: "bapak" },
  { person: "Asma Samik Ibrahim", related_to: "Samik Ibrahim", relationship_type: "bapak" },
  { person: "Laili Roesad", related_to: "Rusad Datuk Perpatih Baringek", relationship_type: "bapak" },
  { person: "Redian Fikri Guspardi", related_to: "Guspardi Gaus", relationship_type: "bapak" },
  { person: "Atta Halilintar", related_to: "Halilintar Anofial Asmid", relationship_type: "bapak" },
  { person: "Emil Salim", related_to: "Baay Salim", relationship_type: "bapak" },
  { person: "Ferdy Salim", related_to: "Baay Salim", relationship_type: "bapak" },
  { person: "Darry Salim", related_to: "Baay Salim", relationship_type: "bapak" },
  { person: "Sutan Sjahrir", related_to: "Mohammad Rasjad", relationship_type: "bapak" },
  { person: "Rohana Kudus", related_to: "Mohammad Rasjad", relationship_type: "bapak" },
  { person: "Soetan Sjahsam", related_to: "Mohammad Rasjad", relationship_type: "bapak" },
  { person: "Poeti Siti Sjahrizad", related_to: "Mohammad Rasjad", relationship_type: "bapak" },
  { person: "Radena", related_to: "Mohammad Rasjad", relationship_type: "bapak" },
  { person: "Soetan Noeralamsjah", related_to: "Mohammad Rasjad", relationship_type: "bapak" },
  { person: "Mahroezar", related_to: "Mohammad Rasjad", relationship_type: "bapak" },
  { person: "Soetan Soeleimansjah", related_to: "Mohammad Rasjad", relationship_type: "bapak" },
  { person: "Mohammad Rasjad", related_to: "Leman Sutan Palindih", relationship_type: "bapak" },
  { person: "Abdul Gani Rajo Mangkuto", related_to: "Syekh Abdoellah", relationship_type: "bapak" },
  { person: "Leman Sutan Palindih", related_to: "Syekh Abdoellah", relationship_type: "bapak" },
  { person: "Abdoel Rachman", related_to: "Syekh Abdoellah", relationship_type: "bapak" },
  { person: "Kanya Stira", related_to: "Kriya Arsyah Sjahrir", relationship_type: "bapak" },
  { person: "Igor Tamerlan", related_to: "Moehamad Akbar Djoehana", relationship_type: "bapak" },
  { person: "Wiya Pane", related_to: "Ilya Arslaan Sjahroezah", relationship_type: "bapak" },
  { person: "Sutan Mohamad Salim", related_to: "Abdoel Rachman", relationship_type: "bapak" },
  { person: "Siti Marjam", related_to: "Abdoel Rachman", relationship_type: "bapak" },
  { person: "Zainatun Nahar", related_to: "Almatsier", relationship_type: "bapak" },
  { person: "Hazniel Almatsier", related_to: "Almatsier", relationship_type: "bapak" },
  { person: "Sunita Almatsier", related_to: "Almatsier", relationship_type: "bapak" },
  { person: "Almatsier", related_to: "Karana Injik Hitam Bagindo Poetih", relationship_type: "bapak" },
  { person: "Jezzie Setiawan", related_to: "Budi Setiawan", relationship_type: "bapak" },
  { person: "Adelina Setiawan", related_to: "Budi Setiawan", relationship_type: "bapak" },
  { person: "Fariz Rustam Munaf", related_to: "Roestam Moenaf", relationship_type: "bapak" },
  { person: "Asikin Hanafiah", related_to: "Ali Hanafiah", relationship_type: "bapak" },
  { person: "Sitti Raham", related_to: "Rasul St. Redjo Endah", relationship_type: "bapak" },
  { person: "Diana Kartika", related_to: "Mansyurdin Arma", relationship_type: "bapak" },
  { person: "Hilman Adil", related_to: "Soetan Kali Malikoel Adil", relationship_type: "bapak" },
  { person: "Nurhayati Subakat", related_to: "Abdul Muin Saidi", relationship_type: "bapak" },
  { person: "Nursyirwan Effendi", related_to: "Aminuddin Rasyad", relationship_type: "bapak" },
  { person: "Tuanku Mudo Amin", related_to: "Tuanku Telur Padusunan", relationship_type: "bapak" },
  { person: "Rasul Telur", related_to: "Tuanku Telur Padusunan", relationship_type: "bapak" },
  { person: "Zubir Amin", related_to: "Tuanku Mudo Amin", relationship_type: "bapak" },
  { person: "Aisjah Dahlan", related_to: "Tuanku Mudo Amin", relationship_type: "bapak" },
  { person: "Djamaloeddin", related_to: "Mohamad Amin Datuk Kakayo", relationship_type: "bapak" },
  { person: "Harun Al-Rasyid Sutan Bandaro", related_to: "Mohamad Amin Datuk Kakayo", relationship_type: "bapak" },
  { person: "Ali Emran", related_to: "Mohamad Amin Datuk Kakayo", relationship_type: "bapak" },
  { person: "Lily Sjarif", related_to: "Sjarif Usman", relationship_type: "bapak" },
  { person: "Menaldi Rasmin", related_to: "Rasmin Rasjid", relationship_type: "bapak" },
  { person: "Audy Joinaldy", related_to: "Joinerri Kahar", relationship_type: "bapak" },
  { person: "Kanido Rachman Mashjoer", related_to: "Kahar Masjhoer", relationship_type: "bapak" },
  { person: "Juananda Sutan Assin", related_to: "Mansyur Sutan Assin", relationship_type: "bapak" },
  { person: "Said Djauharsjah Jenie", related_to: "Nahar Jenie", relationship_type: "bapak" },
  { person: "Umar Anggara Jenie", related_to: "Nahar Jenie", relationship_type: "bapak" },
  { person: "Ismijati Jenie", related_to: "Nahar Jenie", relationship_type: "bapak" },
  { person: "Muhammad Naharuddin Jenie", related_to: "Nahar Jenie", relationship_type: "bapak" },
  { person: "Sitti Airiza Jenie", related_to: "Abdoel Azir Jenie", relationship_type: "bapak" },
  { person: "Syahniar Mahnida", related_to: "Zawir Kamaluddin", relationship_type: "bapak" },
  { person: "Ibenzani Usman", related_to: "Usman Kagami", relationship_type: "bapak" },
  { person: "Fadly Amran", related_to: "Amran Sutan Sidi Sulaiman", relationship_type: "bapak" },
  { person: "Hendri Arnis", related_to: "Arnis Saleh", relationship_type: "bapak" },
  { person: "Muhammad Chatib Basri", related_to: "Chairul Basri", relationship_type: "bapak" },
  { person: "Achmad Arief Dt. Majo Urang", related_to: "Djaa Dt. Batuah", relationship_type: "bapak" },
  { person: "Irfan Fachruddin", related_to: "Fachroeddin H. S. Dt. Majoindo", relationship_type: "bapak" },
  { person: "Darius Fachruddin", related_to: "Fachroeddin H. S. Dt. Majoindo", relationship_type: "bapak" },
  { person: "Waruno Mahdi", related_to: "Izak Mahdi", relationship_type: "bapak" },
  { person: "Izak Mahdi", related_to: "Marzoeki Mahdi", relationship_type: "bapak" },
  { person: "Linggakusuma Karim", related_to: "A. Karim", relationship_type: "bapak" },
  { person: "Aswin Manwantara Karim", related_to: "A. Karim", relationship_type: "bapak" },
  { person: "Komala Bahri Karim", related_to: "A. Karim", relationship_type: "bapak" },
  { person: "Rukmini Zainal Abidin", related_to: "Abdul Djalil", relationship_type: "bapak" },
  { person: "Almitra Abidin", related_to: "Zainal Abidin (pengusaha)", relationship_type: "bapak" },
  { person: "Abdul Kuddus", related_to: "Djanaid Dt. Dinagari", relationship_type: "bapak" },
  { person: "Zahir Angku Basa", related_to: "Djanaid Dt. Dinagari", relationship_type: "bapak" },
  { person: "Siti Asidah", related_to: "Djanaid Dt. Dinagari", relationship_type: "bapak" },
  { person: "Busyra Zahir", related_to: "Zahir Angku Basa", relationship_type: "bapak" },
  { person: "Azhar Zahir", related_to: "Zahir Angku Basa", relationship_type: "bapak" },
  { person: "Pipit Sandra", related_to: "Sjamsuddin Sjafei", relationship_type: "bapak" },
  { person: "Rahmah El Yunusiyyah", related_to: "Muhammad Yunus al-Khalidiyah", relationship_type: "bapak" },
  { person: "Zainuddin Labay El Yunusy", related_to: "Muhammad Yunus al-Khalidiyah", relationship_type: "bapak" },
  { person: "Zulkarnaen Djabar", related_to: "Bagindo Djabar", relationship_type: "bapak" },
  { person: "Bobby Rasyidin", related_to: "Asnil Sahim", relationship_type: "bapak" },
  { person: "Cantika Felder", related_to: "Alexander Felder", relationship_type: "bapak" },
  { person: "Catra Chrisandi Felder", related_to: "Alexander Felder", relationship_type: "bapak" },
  { person: "Sutan Remy Sjahdeini", related_to: "Achmad Djohar", relationship_type: "bapak" },
  { person: "Marini Zumarnis", related_to: "Zumarnis Zein", relationship_type: "bapak" },
  { person: "Soesmalijah Soewondo", related_to: "Boestami Sjarif", relationship_type: "bapak" },
  { person: "Ilham Syarif", related_to: "Boestami Sjarif", relationship_type: "bapak" },
  { person: "Puan Maharani", related_to: "Megawati Soekarnoputri", relationship_type: "ibu" },
  { person: "Tini Hadad", related_to: "Sariamin Ismail", relationship_type: "ibu" },
  { person: "Megawati Soekarnoputri", related_to: "Fatmawati", relationship_type: "ibu" },
  { person: "Guruh Soekarnoputra", related_to: "Fatmawati", relationship_type: "ibu" },
  { person: "Sukmawati Soekarnoputri", related_to: "Fatmawati", relationship_type: "ibu" },
  { person: "Guntur Soekarnoputra", related_to: "Fatmawati", relationship_type: "ibu" },
  { person: "Riza Aziz", related_to: "Rosmah Mansor", relationship_type: "ibu" },
  { person: "Nooryana Najwa Najib", related_to: "Rosmah Mansor", relationship_type: "ibu" },
  { person: "Norashman Najib", related_to: "Rosmah Mansor", relationship_type: "ibu" },
  { person: "Azrene Soraya Abdul Aziz", related_to: "Rosmah Mansor", relationship_type: "ibu" },
  { person: "Tunku Naquiyuddin", related_to: "Tuanku Najihah", relationship_type: "ibu" },
  { person: "Tunku Imran", related_to: "Tuanku Najihah", relationship_type: "ibu" },
  { person: "Tunku Nadzaruddin", related_to: "Tuanku Najihah", relationship_type: "ibu" },
  { person: "Tuanku Bahiyah", related_to: "Tunku Kurshiah", relationship_type: "ibu" },
  { person: "Tunku Puteri Intan Safinaz", related_to: "Tuanku Bahiyah", relationship_type: "ibu" },
  { person: "Dewi Irawan", related_to: "Ade Irawan", relationship_type: "ibu" },
  { person: "Ria Irawan", related_to: "Ade Irawan", relationship_type: "ibu" },
  { person: "Tribuana Said", related_to: "Ani Idrus", relationship_type: "ibu" },
  { person: "Rayati Syafrin", related_to: "Ani Idrus", relationship_type: "ibu" },
  { person: "Nazyra C. Noer", related_to: "Jajang C. Noer", relationship_type: "ibu" },
  { person: "Marina Mahathir", related_to: "Siti Hasmah Mohamad Ali", relationship_type: "ibu" },
  { person: "Mokhzani Mahathir", related_to: "Siti Hasmah Mohamad Ali", relationship_type: "ibu" },
  { person: "Mukhriz Mahathir", related_to: "Siti Hasmah Mohamad Ali", relationship_type: "ibu" },
  { person: "Solihin Kalla", related_to: "Mufidah Jusuf Kalla", relationship_type: "ibu" },
  { person: "Chairani Kalla", related_to: "Mufidah Jusuf Kalla", relationship_type: "ibu" },
  { person: "Ricky Harun", related_to: "Donna Harun", relationship_type: "ibu" },
  { person: "Adityawarman", related_to: "Dara Jingga", relationship_type: "ibu" },
  { person: "Akarendrawarman", related_to: "Dara Jingga", relationship_type: "ibu" },
  { person: "Jayanagara", related_to: "Dara Petak", relationship_type: "ibu" },
  { person: "Lia Alizia", related_to: "Elza Syarief", relationship_type: "ibu" },
  { person: "Tengku Resi Revado", related_to: "Erny Tanjung", relationship_type: "ibu" },
  { person: "Zaskia Sungkar", related_to: "Fanny Bauty", relationship_type: "ibu" },
  { person: "Shireen Sungkar", related_to: "Fanny Bauty", relationship_type: "ibu" },
  { person: "Boy G. Sakti", related_to: "Gusmiati Suid", relationship_type: "ibu" },
  { person: "Muhammad Jujur", related_to: "Huriah Adam", relationship_type: "ibu" },
  { person: "Shanti L. Poesposoetjipto", related_to: "Mien Soedarpo", relationship_type: "ibu" },
  { person: "Ratna Djuwita", related_to: "Mien Soedarpo", relationship_type: "ibu" },
  { person: "Almitra Abidin", related_to: "Rukmini Zainal Abidin", relationship_type: "ibu" },
  { person: "Sjahfiri Alim", related_to: "Saadah Alim", relationship_type: "ibu" },
  { person: "Ditta Amahorseya", related_to: "Samiati Alisjahbana", relationship_type: "ibu" },
  { person: "Mien Soedarpo", related_to: "Syarifah Nawawi", relationship_type: "ibu" },
  { person: "Yulia Yahya", related_to: "Asmiar Yahya", relationship_type: "ibu" },
  { person: "Ismet D. Tahir", related_to: "Djilis Tahir", relationship_type: "ibu" },
  { person: "Erick Hariyona", related_to: "Emma Yohanna", relationship_type: "ibu" },
  { person: "Naura Ayu", related_to: "Riafinola Ifani Sari", relationship_type: "ibu" },
  { person: "Neona Ayu", related_to: "Riafinola Ifani Sari", relationship_type: "ibu" },
  { person: "Aida Nurmala", related_to: "Sjamsidar Isa", relationship_type: "ibu" },
  { person: "Harman Subakat", related_to: "Nurhayati Subakat", relationship_type: "ibu" },
  { person: "Salman Subakat", related_to: "Nurhayati Subakat", relationship_type: "ibu" },
  { person: "Sari Chairunnisa", related_to: "Nurhayati Subakat", relationship_type: "ibu" },
  { person: "Kiki Rizky Amelia", related_to: "Pipit Sandra", relationship_type: "ibu" },
  { person: "Linda Amalia Sari", related_to: "Rooslila Tahir", relationship_type: "ibu" },
  { person: "Dali Tahir", related_to: "Rooslila Tahir", relationship_type: "ibu" },
  { person: "Adi Putra Darmawan Tahir", related_to: "Rooslila Tahir", relationship_type: "ibu" },
  { person: "Jose Poernomo", related_to: "Sonya Roesma", relationship_type: "ibu" },
  { person: "Atta Halilintar", related_to: "Lenggogeni Faruk", relationship_type: "ibu" },
  { person: "Ibrahim Irwan Prayitno", related_to: "Nevi Zuairina", relationship_type: "ibu" },
  { person: "Jezzie Setiawan", related_to: "Amelia Farina Salim", relationship_type: "ibu" },
  { person: "Adelina Setiawan", related_to: "Amelia Farina Salim", relationship_type: "ibu" },
  { person: "Dolly Salim", related_to: "Zainatun Nahar", relationship_type: "ibu" },
  { person: "Bibsy Soenharjo", related_to: "Zainatun Nahar", relationship_type: "ibu" },
  { person: "Violet Hanifah Salim", related_to: "Zainatun Nahar", relationship_type: "ibu" },
  { person: "Islam Salim", related_to: "Zainatun Nahar", relationship_type: "ibu" },
  { person: "Rohana Kudus", related_to: "Kiam", relationship_type: "ibu" },
  { person: "Radena", related_to: "Kiam", relationship_type: "ibu" },
  { person: "Sutan Sjahrir", related_to: "Siti Rabiah", relationship_type: "ibu" },
  { person: "Soetan Sjahsam", related_to: "Siti Rabiah", relationship_type: "ibu" },
  { person: "Poeti Siti Sjahrizad", related_to: "Siti Rabiah", relationship_type: "ibu" },
  { person: "Soetan Noeralamsjah", related_to: "Siti Rabiah", relationship_type: "ibu" },
  { person: "Mahroezar", related_to: "Siti Rabiah", relationship_type: "ibu" },
  { person: "Soetan Soeleimansjah", related_to: "Siti Rabiah", relationship_type: "ibu" },
  { person: "Leman Sutan Palindih", related_to: "Kain", relationship_type: "ibu" },
  { person: "Shahrina Tiara Wardhani", related_to: "Siti Rabyah Parvati Sjahrir", relationship_type: "ibu" },
  { person: "Moehamad Akbar Djoehana", related_to: "Poeti Siti Sjahrizad", relationship_type: "ibu" },
  { person: "Djohan Sjahroezah", related_to: "Radena", relationship_type: "ibu" },
  { person: "Gustavo Pane", related_to: "Wiya Pane", relationship_type: "ibu" },
  { person: "Ilya Arslaan Sjahroezah", related_to: "Violet Hanifah Salim", relationship_type: "ibu" },
  { person: "Agus Salim", related_to: "Siti Zainab", relationship_type: "ibu" },
  { person: "Chalid Salim", related_to: "Siti Zainab", relationship_type: "ibu" },
  { person: "Siti Danilah Salim", related_to: "Siti Zainab", relationship_type: "ibu" },
  { person: "Baay Salim", related_to: "Siti Zainab", relationship_type: "ibu" },
  { person: "Zainatun Nahar", related_to: "Siti Marjam", relationship_type: "ibu" },
  { person: "Almatsier", related_to: "Salamah", relationship_type: "ibu" },
  { person: "Nagita Slavina", related_to: "Rita Amelia", relationship_type: "ibu" },
  { person: "Abdul Karim Amrullah", related_to: "Tarwasa", relationship_type: "ibu" },
  { person: "Reza Vector", related_to: "Tengku Resi Revado", relationship_type: "ibu" },
  { person: "Alya Avivah", related_to: "Tengku Resi Revado", relationship_type: "ibu" },
  { person: "Rusydi Hamka", related_to: "Sitti Raham", relationship_type: "ibu" },
  { person: "Irfan Hamka", related_to: "Sitti Raham", relationship_type: "ibu" },
  { person: "Aliyah Hamka", related_to: "Sitti Raham", relationship_type: "ibu" },
  { person: "Afif Hamka", related_to: "Sitti Raham", relationship_type: "ibu" },
  { person: "Fathiyah Hamka", related_to: "Sitti Raham", relationship_type: "ibu" },
  { person: "Amir Syakib", related_to: "Sitti Raham", relationship_type: "ibu" },
  { person: "Sitti Raham", related_to: "Sitti Banum", relationship_type: "ibu" },
  { person: "Nurhayati Subakat", related_to: "Nurjanah", relationship_type: "ibu" },
  { person: "Rahmah El Yunusiyyah", related_to: "Rafiah", relationship_type: "ibu" },
  { person: "Zainuddin Labay El Yunusy", related_to: "Rafiah", relationship_type: "ibu" },
  { person: "Iwan Tirta", related_to: "Ramah Saleh", relationship_type: "ibu" },
  { person: "Siti Dewi Sutan Assin", related_to: "Limbak Tjahaja", relationship_type: "ibu" },
  { person: "Mansyur Sutan Assin", related_to: "Limbak Tjahaja", relationship_type: "ibu" },
  { person: "Mawardi Waly", related_to: "Rabi'ah Jamil", relationship_type: "ibu" },
  { person: "Syahniar Mahnida", related_to: "Siti Amar Jenie", relationship_type: "ibu" },
  { person: "Abdul Kuddus", related_to: "Kalasoen", relationship_type: "ibu" },
  { person: "Dendy Prasetya", related_to: "Elzarita", relationship_type: "ibu" },
  { person: "Indah Nugrahani", related_to: "Elzarita", relationship_type: "ibu" },
  { person: "Zulkarnaen Djabar", related_to: "Sawiyah", relationship_type: "ibu" },
  { person: "Bonita", related_to: "Herdawati Bakrie", relationship_type: "ibu" },
  { person: "Anda Perdana", related_to: "Herdawati Bakrie", relationship_type: "ibu" },
  { person: "Ilham Aidit", related_to: "Soetanti", relationship_type: "ibu" },
  { person: "Patra Azwar", related_to: "Suarni Azwar", relationship_type: "ibu" },
  { person: "Hilman Adil", related_to: "Siti Nurdjanah", relationship_type: "ibu" },
  { person: "Taufiq Kiemas", related_to: "Megawati Soekarnoputri", relationship_type: "pasangan" },
  { person: "Zainatun Nahar", related_to: "Agus Salim", relationship_type: "pasangan" },
  { person: "Tunku Kurshiah", related_to: "Abdul Rahman dari Negeri Sembilan", relationship_type: "pasangan" },
  { person: "Soetanti", related_to: "D. N. Aidit", relationship_type: "pasangan" },
  { person: "Tuanku Najihah", related_to: "Ja'afar dari Negeri Sembilan", relationship_type: "pasangan" },
  { person: "Sunarsih", related_to: "Abdul Muis", relationship_type: "pasangan" },
  { person: "Teuku Umar", related_to: "Cut Nya' Dhien", relationship_type: "pasangan" },
  { person: "Cut Nya' Dhien", related_to: "Teuku Umar", relationship_type: "pasangan" },
  { person: "Raudha Thaib", related_to: "Wisran Hadi", relationship_type: "pasangan" },
  { person: "Megawati Soekarnoputri", related_to: "Taufiq Kiemas", relationship_type: "pasangan" },
  { person: "Ja'afar dari Negeri Sembilan", related_to: "Tuanku Najihah", relationship_type: "pasangan" },
  { person: "Abdul Rahman dari Negeri Sembilan", related_to: "Tunku Kurshiah", relationship_type: "pasangan" },
  { person: "Nevi Zuairina", related_to: "Irwan Prayitno", relationship_type: "pasangan" },
  { person: "Abdul Kuddus", related_to: "Rohana Kudus", relationship_type: "pasangan" },
  { person: "Mukhniarti Basko", related_to: "Basrizal Koto", relationship_type: "pasangan" },
  { person: "Harry Capri", related_to: "Camelia Malik", relationship_type: "pasangan" },
  { person: "Ernest Fardiyan Sjarif", related_to: "Nirina Zubir", relationship_type: "pasangan" },
  { person: "Sitti Raham", related_to: "Hamka", relationship_type: "pasangan" },
  { person: "Tarwasa", related_to: "Muhammad Amrullah", relationship_type: "pasangan" },
  { person: "Duski Samad", related_to: "Rasuna Said", relationship_type: "pasangan" },
  { person: "Dennis Rizky", related_to: "Thalita Latief", relationship_type: "pasangan" },
  { person: "Sativa Sutan Aswar", related_to: "Arif Arryman", relationship_type: "pasangan" },
  { person: "Muhammad Lutfi", related_to: "Bianca Adinegoro", relationship_type: "pasangan" },
  { person: "Thalita Latief", related_to: "Dennis Rizky", relationship_type: "pasangan" },
  { person: "Violet Hanifah Salim", related_to: "Djohan Sjahroezah", relationship_type: "pasangan" },
  { person: "Nazif Basir", related_to: "Elly Kasim", relationship_type: "pasangan" },
  { person: "Nirina Zubir", related_to: "Ernest Fardiyan Sjarif", relationship_type: "pasangan" },
  { person: "Camelia Malik", related_to: "Harry Capri", relationship_type: "pasangan" },
  { person: "Ratna Maida Ning", related_to: "Hasyim Ning", relationship_type: "pasangan" },
  { person: "Bianca Adinegoro", related_to: "Muhammad Lutfi", relationship_type: "pasangan" },
  { person: "Elly Kasim", related_to: "Nazif Basir", relationship_type: "pasangan" },
  { person: "Risty Tagor", related_to: "Rifky Balweel", relationship_type: "pasangan" },
  { person: "Rifky Balweel", related_to: "Risty Tagor", relationship_type: "pasangan" },
  { person: "Zainal Abidin (pengusaha)", related_to: "Rukmini Zainal Abidin", relationship_type: "pasangan" },
  { person: "Siti Danilah Salim", related_to: "Sjamsuddin Sutan Makmur", relationship_type: "pasangan" },
  { person: "Rusydi Malik", related_to: "Zulmiar Yanri", relationship_type: "pasangan" },
  { person: "Nila Moeloek", related_to: "Farid Anfasa Moeloek", relationship_type: "pasangan" },
  { person: "Farid Anfasa Moeloek", related_to: "Nila Moeloek", relationship_type: "pasangan" },
  { person: "Wisran Hadi", related_to: "Raudha Thaib", relationship_type: "pasangan" },
  { person: "Lanjumin Dt. Tumangguang", related_to: "Chailan Syamsu", relationship_type: "pasangan" },
  { person: "Nikita Mirzani", related_to: "Dipo Latief", relationship_type: "pasangan" },
  { person: "Betti Shadiq Pasadigoe", related_to: "M. Shadiq Pasadigoe", relationship_type: "pasangan" },
  { person: "Dipo Latief", related_to: "Nikita Mirzani", relationship_type: "pasangan" },
  { person: "Elzarita", related_to: "Zulkarnaen Djabar", relationship_type: "pasangan" },
  { person: "Yusrida Yusuf", related_to: "Zulkarnain", relationship_type: "pasangan" },
  { person: "Bonny Z. Minang", related_to: "Perdana Putra Minang", relationship_type: "anak" },
  { person: "Syekh Abdoellah", related_to: "Abdul Gani Rajo Mangkuto", relationship_type: "anak" },
  { person: "Mohamad Razif", related_to: "Ahlan B. Razif", relationship_type: "anak" },
  { person: "Sjamsidar Isa", related_to: "Aida Nurmala", relationship_type: "anak" },
  { person: "Ferdy Salim", related_to: "Aidil Chandra Salim", relationship_type: "anak" },
  { person: "Dara Jingga", related_to: "Akarendrawarman", relationship_type: "anak" },
  { person: "Jahja Datoek Kajo", related_to: "Akhiroel Jahja", relationship_type: "anak" },
  { person: "Mochtar Naim", related_to: "Amelia Naim Indrajaya", relationship_type: "anak" },
  { person: "Radin dari Negeri Sembilan", related_to: "Antah dari Negeri Sembilan", relationship_type: "anak" },
  { person: "Sutan Mohammad Rasjid", related_to: "Arwin Rasyid", relationship_type: "anak" },
  { person: "Herdawati Bakrie", related_to: "Bonita", relationship_type: "anak" },
  { person: "Gusmiati Suid", related_to: "Boy G. Sakti", relationship_type: "anak" },
  { person: "Sutan Mohamad Salim", related_to: "Chalid Salim", relationship_type: "anak" },
  { person: "Siti Zainab", related_to: "Chalid Salim", relationship_type: "anak" },
  { person: "Srimat Tribhuwanaraja Mauli Warmadewa", related_to: "Dara Petak", relationship_type: "anak" },
  { person: "Khaidir Anwar", related_to: "Dewi Fortuna Khaidir Anwar", relationship_type: "anak" },
  { person: "Ade Irawan", related_to: "Dewi Irawan", relationship_type: "anak" },
  { person: "Hasyim Djalal", related_to: "Dino Patti Djalal", relationship_type: "anak" },
  { person: "Mohamad Amin Datuk Kakayo", related_to: "Djamaloeddin", relationship_type: "anak" },
  { person: "Radena", related_to: "Djohan Sjahroezah", relationship_type: "anak" },
  { person: "Fahmi Idris", related_to: "Fahira Fahmi Idris", relationship_type: "anak" },
  { person: "Mohammad Hatta", related_to: "Halida Hatta", relationship_type: "anak" },
  { person: "Sutan Adam Bachtiar", related_to: "Harsja W. Bachtiar", relationship_type: "anak" },
  { person: "Sutan Muhammad Zain", related_to: "Harun Al-Rasjid Zain", relationship_type: "anak" },
  { person: "Mohamad Amin Datuk Kakayo", related_to: "Harun Al-Rasyid Sutan Bandaro", relationship_type: "anak" },
  { person: "Adam B.B.", related_to: "Huriah Adam", relationship_type: "anak" },
  { person: "Fachroeddin H. S. Dt. Majoindo", related_to: "Irfan Fachruddin", relationship_type: "anak" },
  { person: "Rooslila Tahir", related_to: "Linda Amalia Sari", relationship_type: "anak" },
  { person: "Abdul Jalil Syah dari Siak", related_to: "Mahmud dari Siak", relationship_type: "anak" },
  { person: "Daud Rasyidi", related_to: "Mansoer Daoed Dt. Palimo Kayo", relationship_type: "anak" },
  { person: "Zumarnis Zein", related_to: "Marini Zumarnis", relationship_type: "anak" },
  { person: "Syarifah Nawawi", related_to: "Mien Soedarpo", relationship_type: "anak" },
  { person: "Sutan Takdir Alisjahbana", related_to: "Mirta Kartohadiprodjo", relationship_type: "anak" },
  { person: "Mohammad Isa Sutan Bandaro", related_to: "Mohammad Nazir", relationship_type: "anak" },
  { person: "Chairul Basri", related_to: "Muhammad Chatib Basri", relationship_type: "anak" },
  { person: "Firdaus Wadjdi", related_to: "Muhammad Lutfi", relationship_type: "anak" },
  { person: "Dahlan Ibrahim", related_to: "Murnizal Dahlan", relationship_type: "anak" },
  { person: "Rita Amelia", related_to: "Nagita Slavina", relationship_type: "anak" },
  { person: "Nas Achnas", related_to: "Nan Achnas", relationship_type: "anak" },
  { person: "Lenggang dari Negeri Sembilan", related_to: "Radin dari Negeri Sembilan", relationship_type: "anak" },
  { person: "Oesman Sapta Odang", related_to: "Raja Sapta Oktohari", relationship_type: "anak" },
  { person: "Adlinsjah Jenie", related_to: "Rezlan Ishar Jenie", relationship_type: "anak" },
  { person: "Ade Irawan", related_to: "Ria Irawan", relationship_type: "anak" },
  { person: "Abdul Djalil", related_to: "Rukmini Zainal Abidin", relationship_type: "anak" },
  { person: "Hamka", related_to: "Rusydi Hamka", relationship_type: "anak" },
  { person: "Sitti Raham", related_to: "Rusydi Hamka", relationship_type: "anak" },
  { person: "Nahar Jenie", related_to: "Said Djauharsjah Jenie", relationship_type: "anak" },
  { person: "Sutan Takdir Alisjahbana", related_to: "Samiati Alisjahbana", relationship_type: "anak" },
  { person: "Mien Soedarpo", related_to: "Shanti L. Poesposoetjipto", relationship_type: "anak" },
  { person: "Abbas Qadhi Ladang Laweh", related_to: "Sirajuddin Abbas", relationship_type: "anak" },
  { person: "Sutan Takdir Alisjahbana", related_to: "Sofyan Alisjahbana", relationship_type: "anak" },
  { person: "Sutan Takdir Alisjahbana", related_to: "Sri Artaria Alisjahbana", relationship_type: "anak" },
  { person: "Misbach Yusa Biran", related_to: "Sukma Ayu", relationship_type: "anak" },
  { person: "Fatmawati", related_to: "Sukmawati Soekarnoputri", relationship_type: "anak" },
  { person: "Soekarno M. Noer", related_to: "Suti Karno", relationship_type: "anak" },
  { person: "Nawawi Soetan Makmoer", related_to: "Syarifah Nawawi", relationship_type: "anak" },
  { person: "Taher Marah Soetan", related_to: "Tarmizi Taher", relationship_type: "anak" },
  { person: "Ja'afar dari Negeri Sembilan", related_to: "Tunku Imran", relationship_type: "anak" },
  { person: "Tuanku Najihah", related_to: "Tunku Imran", relationship_type: "anak" },
  { person: "Nahar Jenie", related_to: "Umar Anggara Jenie", relationship_type: "anak" },
  { person: "M. Shadiq Pasadigoe", related_to: "Betti Shadiq Pasadigoe", relationship_type: "pasangan" },
  { person: "Chailan Syamsu", related_to: "Lanjumin Dt. Tumangguang", relationship_type: "pasangan" },
  { person: "Hasyim Ning", related_to: "Ratna Maida Ning", relationship_type: "pasangan" },
  { person: "Arif Arryman", related_to: "Sativa Sutan Aswar", relationship_type: "pasangan" },
  { person: "Sjamsuddin Sutan Makmur", related_to: "Siti Danilah Salim", relationship_type: "pasangan" },
  { person: "Abdul Muin Datuk Rangkayo Maharajo", related_to: "Syamsidar Yahya", relationship_type: "pasangan" },
  { person: "Siti Zainab", related_to: "Sutan Mohamad Salim", relationship_type: "pasangan" },
  { person: "Halilintar Anofial Asmid", related_to: "Lenggogeni Faruk", relationship_type: "pasangan" },
  { person: "Basrizal Koto", related_to: "Mukhniarti Basko", relationship_type: "pasangan" },
  { person: "Limbak Tjahaja", related_to: "Sutan Assin", relationship_type: "pasangan" },
  { person: "Rabi'ah Jamil", related_to: "Muhammad Waly Al-Khalidy", relationship_type: "pasangan" },
  { person: "Syuhendri", related_to: "Zurmailis", relationship_type: "pasangan" },
  { person: "Irwan Prayitno", related_to: "Nevi Zuairina", relationship_type: "pasangan" },
  { person: "Lenggogeni Faruk", related_to: "Halilintar Anofial Asmid", relationship_type: "pasangan" },
];

function getNormalizedData(raw: FamilyRelation[]): FamilyRelation[] {
  const normalized: FamilyRelation[] = [];
  const seenPairs = new Set<string>();

  raw.forEach((rel) => {
    // 1. Skip "anak" relations as they are fully redundant with "bapak" / "ibu"
    if (rel.relationship_type === "anak") {
      return;
    }

    const p = rel.person.trim();
    const r = rel.related_to.trim();
    const t = rel.relationship_type;

    let pairKey = "";
    if (t === "pasangan") {
      // For spouses, A-B is the same as B-A. Sort alphabetically to create a unique key.
      const sorted = [p, r].sort();
      pairKey = `pasangan:${sorted[0]}:${sorted[1]}`;
    } else {
      pairKey = `${t}:${p}:${r}`;
    }

    if (!seenPairs.has(pairKey)) {
      seenPairs.add(pairKey);
      normalized.push({
        person: p,
        related_to: r,
        relationship_type: t
      });
    }
  });

  return normalized;
}

export const familyData = getNormalizedData(rawFamilyData);

export interface PersonRelations {
  fathers: string[];
  mothers: string[];
  spouses: string[];
  children: string[];
}

export const personRelationsLookup: Record<string, PersonRelations> = {};

const namesSet = new Set<string>();

function getOrCreateRelations(name: string): PersonRelations {
  if (!personRelationsLookup[name]) {
    personRelationsLookup[name] = {
      fathers: [],
      mothers: [],
      spouses: [],
      children: []
    };
  }
  return personRelationsLookup[name];
}

// Populate pre-indexed lookup map using normalized data
familyData.forEach((rel) => {
  const p = rel.person;
  const r = rel.related_to;
  const type = rel.relationship_type;

  namesSet.add(p);
  namesSet.add(r);

  const pRels = getOrCreateRelations(p);
  const rRels = getOrCreateRelations(r);

  if (type === "bapak") {
    if (!pRels.fathers.includes(r)) pRels.fathers.push(r);
    if (!rRels.children.includes(p)) rRels.children.push(p);
  } else if (type === "ibu") {
    if (!pRels.mothers.includes(r)) pRels.mothers.push(r);
    if (!rRels.children.includes(p)) rRels.children.push(p);
  } else if (type === "pasangan") {
    if (!pRels.spouses.includes(r)) pRels.spouses.push(r);
    if (!rRels.spouses.includes(p)) rRels.spouses.push(p);
  }
});

// Export unique sorted names
export const allUniqueNames = Array.from(namesSet).sort();

export const relationshipLabels: Record<string, string> = {
  bapak: "Father",
  ibu: "Mother",
  pasangan: "Spouse",
  anak: "Child",
};

export const relationshipColors: Record<string, string> = {
  bapak: "#3b82f6",
  ibu: "#ec4899",
  pasangan: "#22c55e",
  anak: "#f59e0b",
};
